## task
name: 'motion quantization'

## train
train:
  lr: 5e-5
  batch_size: 256
  num_workers: 4
  max_steps: 300000 # max steps to train
  log_every_step: 200 # log every ${log_every_step} steps
  save_every_step: 50000 # save model every ${save_every_step} steps
  test_every_step: 1000
  phase: 'all' # train or all

  resume_ckpt: '' # resume from checkpoint
  weight_decay: 0.0
  lr_anneal_steps: 0
  schedule_sampler_type: 'uniform'

  loss_level: 0.1
  loss_vq: 0.01

## test
test:
  batch_size: 32
  num_workers: 0
  contact_folder: ''

## sample
sample:
  batch_size: 8
  num_workers: 0
  dataset_name: 'ContactMotionExampleDataset'
  data_path: './data/examples/contact_motion_examples.txt'
  contact_folder: ''

## dataset
dataset:
  name: 'ContactMotionDataset'
  data_dir: './data'
  shuffle_seed: ${seed}
  sets: ['HUMANISE'] # ['HumanML3D', 'HUMANISE', 'PROX']
  sets_config:
    HUMANISE:
      ratio: 1.0 # the ratio of the dataset to use
      load_text: true
  
  data_repr: ${model.data_repr}
  contact_type: ${model.contact_model.contact_type}
  contact_joints: ${model.contact_model.contact_joints}
  use_raw_dist: false
  sigma: 0.5
  num_points: 8192
  min_horizon: 24
  max_horizon: 132
  mix_train_ratio: 0.0

  contact_folder: ''

  ## transforms
  train_transforms: ['RandomRotation', 'ApplyTransformCMDM', 'NumpyToTensor']
  test_transforms: ['NumpyToTensor']
  transform_cfg:
    gravity_dim: 2
    random_mask_prob: 0.1
    random_mask_prob_pc: 0.1

  ## dataset
test_dataset:
  name: 'MotionDataset'
  data_dir: './data'
  shuffle_seed: ${seed}
  sets: ['HUMANISE'] # ['HumanML3D', 'HUMANISE', 'PROX']
  sets_config:
    HUMANISE:
      ratio: 1.0 # the ratio of the dataset to use
      load_text: true
  
  data_repr: ${model.data_repr}
  contact_type: ${model.contact_model.contact_type}
  contact_joints: ${model.contact_model.contact_joints}
  use_raw_dist: false
  sigma: 0.5
  num_points: 8192
  min_horizon: 24
  max_horizon: 132
  mix_train_ratio: 0.0

  contact_folder: ''

  ## transforms
  train_transforms: ['RandomRotation', 'ApplyTransformCMDM', 'NumpyToTensor']
  test_transforms: ['NumpyToTensor']
  transform_cfg:
    gravity_dim: 2
    random_mask_prob: 0.1
    random_mask_prob_pc: 0.1
  
## for visualization
visualizer:
  name: 'ContactMotionVisualizer'
  njoints: 22

## for evaluation
evaluator:
  name: 'Text2MotionInSceneEvaluator'
  njoints: 22

  k_samples: 1
  num_k_samples: 10
  eval_nbatch: 100
  eval_metrics: ['apd', 'non_collision', 'contact', 'dist']
  save_results: true

  ## for optimize joints
  opt_rate: 0.02
  opt_steps: 200
  joints_to_smplx_model_weights: './utils/joints_to_smplx/060.pt'